### ISSUE TITLE
PL chars

### ISSUE THREAD

**Issue by henkedk** [BenMorel/GsmCharsetConverter#1]
I have no idea how to submit on Git, but here's a transliteration for polish chars I needed done.

        "\u{0105}" => "\u{0061}",
        "\u{0104}" => "\u{0041}",
        "\u{0107}" => "\u{0063}",
        "\u{0106}" => "\u{0043}",
        "\u{0119}" => "\u{0065}",
        "\u{0118}" => "\u{0045}",
        "\u{0142}" => "\u{006C}",
        "\u{0141}" => "\u{004C}",
        "\u{0144}" => "\u{006E}",
        "\u{0143}" => "\u{004E}",
        "\u{015b}" => "\u{0073}",
        "\u{015a}" => "\u{0053}",
        "\u{017a}" => "\u{007A}",
        "\u{0179}" => "\u{005A}",
        "\u{017c}" => "\u{007A}",
        "\u{017b}" => "\u{005A}",

**Comment by BenMorel** [comment]
Thank you! Implemented and released as [0.1.1](https://github.com/BenMorel/GsmCharsetConverter/releases/tag/0.1.1).
