### ISSUE TITLE
Romanian chars

### ISSUE THREAD

**Issue by axwell** [BenMorel/GsmCharsetConverter#3]
Can you please add romanian chars?

"\u{0218}" => "\u{0053}", // S
"\u{0219}" => "\u{0073}", // s
"\u{021a}" => "\u{0054}", // T
"\u{021b}" => "\u{0074}", // t
"\u{0102}" => "\u{0041}", // A
"\u{0103}" => "\u{0061}", // a
"\u{00C2}" => "\u{0041}", // A
"\u{00e2}" => "\u{0061}", // a
"\u{00ce}" => "\u{0049}", // I
"\u{00ee}" => "\u{0069}", // i

**Comment by BenMorel** [comment]
Done! Released in [0.2.1](https://github.com/BenMorel/GsmCharsetConverter/releases/tag/0.2.1).

Note that the last 4 chars (circumflexes) were already supported.
